#!/usr/bin/env bash
mkdir -p ~/dotsimple/nvim/.config/nvim/plugin
mkdir -p ~/dotsimple/nvim/.config/nvim/after/plugin
mkdir -p ~/dotsimple/nvim/.config/nvim/lua

# link wholesale
#for f in `find . -regex ".*\.vim$\|.*\.lua$"`; do
#    rm -rf ~/.config/nvim/$f
#    ln -s ~/dotfiles/awesome-streamerrc/ThePrimeagen/$f ~/.config/nvim/$f
#done

